# Generated by Django 4.1.7 on 2023-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='organisation_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='recruitment_agency',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='degree_classification',
            field=models.CharField(blank=True, choices=[('FIRST', 'First Class Honours'), ('SECOND_UPPER', 'Second Class Honours(upper)'), ('SECOND_LOWER', 'Second Class Honours(lower)'), ('THIRD', 'Third Class Honours')], default='Female', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Bachelors'), ('POSTGRADUATE(T)', 'Masters'), ('POSTGRADUATE(R)', 'Doctorate'), ('OLEVEL', 'Senior Secondary Certificate'), ('HND', 'Higher National Diploma')], default='Female', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='subject_of_study',
            field=models.CharField(blank=True, choices=[('COMPUTER_SCIENCE', 'Computer Science'), ('PETROLEUM_ENGINEERING', 'Petroleum Engineering'), ('PHARMACY', 'Pharmacy'), ('ECONOMICS', 'Economics'), ('LAW', 'Law')], default='Female', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='university_name',
            field=models.CharField(blank=True, choices=[('BABCOCK_UNIVERSITY', 'Babcock University'), ('UNILAG', 'University of Lagos'), ('UNIBEN', 'University of Benin'), ('ABUAD', 'Afe Babalola University Ado-Ekiti'), ('YABATECH', 'Yaba College Of Technology'), ('BOWEN', 'Bowen University')], default='Female', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='year_of_graduation',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], default='Female', max_length=200, null=True),
        ),
    ]
