# Generated by Django 4.1.7 on 2023-04-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employer_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='recruitment_agency',
            field=models.BooleanField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='degree_classification',
            field=models.CharField(blank=True, choices=[('FIRST', 'First Class Honours'), ('SECOND_UPPER', 'Second Class Honours(upper)'), ('SECOND_LOWER', 'Second Class Honours(lower)'), ('THIRD', 'Third Class Honours')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Bachelors'), ('POSTGRADUATE(T)', 'Masters'), ('POSTGRADUATE(R)', 'Doctorate'), ('OLEVEL', 'Senior Secondary Certificate'), ('HND', 'Higher National Diploma')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='subject_of_study',
            field=models.CharField(blank=True, choices=[('COMPUTER_SCIENCE', 'Computer Science'), ('PETROLEUM_ENGINEERING', 'Petroleum Engineering'), ('PHARMACY', 'Pharmacy'), ('ECONOMICS', 'Economics'), ('LAW', 'Law')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='university_name',
            field=models.CharField(blank=True, choices=[('BABCOCK_UNIVERSITY', 'Babcock University'), ('UNILAG', 'University of Lagos'), ('UNIBEN', 'University of Benin'), ('ABUAD', 'Afe Babalola University Ado-Ekiti'), ('YABATECH', 'Yaba College Of Technology'), ('BOWEN', 'Bowen University')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='year_of_graduation',
            field=models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
