# Generated by Django 4.1.7 on 2023-04-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0003_job_application_deadline_job_cv_requirement_and_more'),
        ('JobSeekers', '0002_jobseeker_alter_applicantcredential_job_seeker'),
        ('authentication', '0003_alter_employer_recruitment_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
