# Generated by Django 4.1.7 on 2023-04-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_employer_recruitment_agency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(max_length=30)),
                ('credential', models.FileField(upload_to='credentials/')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('skills_required', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('REMOTE', 'Remote'), ('ENTRY_LEVEL', 'Entry Level'), ('INTERNSHIP', 'Internship')], default='Full Time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employer')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationStatus', models.CharField(choices=[('ACCEPTED', 'accepted'), ('INTERVIEW', 'interview'), ('OFFER_SENT', 'offer sent'), ('DECLINED', 'declined'), ('OFFER_DECLINED', 'offer unaccepted'), ('IN_REVIEW', 'in review')], default='new', max_length=30)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employers.applicantcredential')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employers.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.jobseeker')),
            ],
        ),
    ]
