# Generated by Django 4.1.7 on 2023-04-17 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Accepted', 'Accepted'), ('Interview', 'Interview'), ('Declined', 'Declined'), ('In Review', 'In Review')], default='In Review')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('gender', models.TextField(choices=[('Female', 'Female'), ('Male', 'Male')])),
                ('job_title', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=12)),
                ('organisation_name', models.CharField(max_length=225)),
                ('office_address', models.CharField(max_length=225)),
                ('organisation_description', models.CharField(blank=True, max_length=225, null=True)),
                ('website', models.CharField(blank=True, max_length=225, null=True)),
                ('employees', models.IntegerField()),
                ('recruitment_agency', models.BooleanField(blank=True, default=False, max_length=200, null=True)),
                ('industry', models.CharField(max_length=225)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Employer_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('job_post_duration', models.DateField(default=None)),
                ('salary', models.FloatField()),
                ('pay_rate', models.TextField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Hourly', 'Hourly')], default='Monthly')),
                ('skills_required', models.CharField(max_length=200)),
                ('job_type', models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default=None)),
                ('open_spots', models.IntegerField(default=0)),
                ('application_deadline', models.DateTimeField(default=None)),
                ('degree_classification', models.TextField(choices=[('First Class Honours', 'First'), ('Second Class Honours(upper)', 'Second Upper'), ('Second Class Honours(lower)', 'Second Lower'), ('Third Class Honours', 'Third')], default=None)),
                ('is_available', models.BooleanField(default=False)),
                ('cv_requirement', models.BooleanField(default=False)),
                ('resumption', models.DateField(default=None)),
                ('is_remote_opportunity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('urgency', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='Employers.employer')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
