# Generated by Django 4.1.7 on 2023-04-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='credential',
        ),
        migrations.DeleteModel(
            name='ApplicantCredential',
        ),
    ]
