# Generated by Django 4.1.7 on 2023-04-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
