# Generated by Django 4.1.7 on 2023-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('Employers', '0002_initial 2'),
        ('Employers', '0003_delete_applicant'),
    ]

    operations = [
    ]
