# Generated by Django 4.1.7 on 2023-04-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0003_job_application_deadline_job_cv_requirement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
