# Generated by Django 4.1.7 on 2023-04-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0004_merge_0002_initial 2_0003_delete_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
