# Generated by Django 4.1.7 on 2023-04-28 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0005_remove_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
