# Generated by Django 4.1.7 on 2023-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0006_alter_job_application_deadline_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
