# Generated by Django 4.1.7 on 2023-05-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0008_employer_company_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='organisation_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
