# Generated by Django 4.1.7 on 2023-04-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_employer_recruitment_agency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_name', models.CharField(max_length=30)),
                ('credential', models.FileField(upload_to='credentials/')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.jobseeker')),
            ],
        ),
    ]
