# Generated by Django 4.1.7 on 2023-04-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobSeekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('university_name', models.CharField(blank=True, choices=[('BABCOCK_UNIVERSITY', 'Babcock University'), ('UNILAG', 'University of Lagos'), ('UNIBEN', 'University of Benin'), ('ABUAD', 'Afe Babalola University Ado-Ekiti'), ('YABATECH', 'Yaba College Of Technology'), ('BOWEN', 'Bowen University')], max_length=200, null=True)),
                ('subject_of_study', models.CharField(blank=True, choices=[('COMPUTER_SCIENCE', 'Computer Science'), ('PETROLEUM_ENGINEERING', 'Petroleum Engineering'), ('PHARMACY', 'Pharmacy'), ('ECONOMICS', 'Economics'), ('LAW', 'Law')], max_length=200, null=True)),
                ('year_of_graduation', models.CharField(blank=True, choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=200, null=True)),
                ('degree_classification', models.TextField(choices=[('First Class Honours', 'First'), ('Second Class Honours(upper)', 'Second Upper'), ('Second Class Honours(lower)', 'Second Lower'), ('Third Class Honours', 'Third')])),
                ('highest_qualification', models.CharField(choices=[('UNDERGRADUATE', 'Bachelors'), ('POSTGRADUATE(T)', 'Masters'), ('POSTGRADUATE(R)', 'Doctorate'), ('OLEVEL', 'Senior Secondary Certificate'), ('HND', 'Higher National Diploma')], max_length=200, null=True)),
                ('gender', models.TextField(choices=[('Female', 'Female'), ('Male', 'Male')])),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobSeeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='applicantcredential',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekers.jobseeker'),
        ),
    ]
