# Generated by Django 4.1.7 on 2023-04-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
