# Generated by Django 4.1.7 on 2023-04-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0004_delete_jobapplication'),
        ('JobSeekers', '0002_jobseeker_alter_applicantcredential_job_seeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationStatus', models.CharField(choices=[('ACCEPTED', 'accepted'), ('INTERVIEW', 'interview'), ('OFFER_SENT', 'offer sent'), ('DECLINED', 'declined'), ('OFFER_DECLINED', 'offer unaccepted'), ('IN_REVIEW', 'in review')], default='new', max_length=30)),
                ('credential', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JobSeekers.applicantcredential')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employers.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobSeekers.jobseeker')),
            ],
        ),
    ]
