# Generated by Django 4.1.7 on 2023-04-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0005_alter_employer_user_alter_job_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobSeekers', '0004_alter_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantcredential',
            name='credential',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AlterField(
            model_name='applicantcredential',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to='JobSeekers.jobseeker'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='credential',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_credential', to='JobSeekers.applicantcredential'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='Employers.job'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Seeker', to='JobSeekers.jobseeker'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobSeeker', to=settings.AUTH_USER_MODEL),
        ),
    ]
