# Generated by Django 4.1.7 on 2023-04-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0005_alter_applicantcredential_credential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicationStatus',
        ),
    ]
