# Generated by Django 4.1.7 on 2023-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0005_jobseeker_nin_jobseeker_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='nin',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
