# Generated by Django 4.1.7 on 2023-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0007_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.TextField(blank=True, choices=[('Accepted', 'Accepted'), ('Interview', 'Interview'), ('Declined', 'Declined'), ('In Review', 'In Review')], default='In Review'),
        ),
    ]
