# Generated by Django 4.1.7 on 2023-04-24 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employers', '0005_remove_job_recruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobSeekers', '0009_savedjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedJobs',
            new_name='SavedJob',
        ),
    ]
