# Generated by Django 4.1.7 on 2023-04-24 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0010_rename_savedjobs_savedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_seeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobseeker', to='JobSeekers.jobseeker'),
            preserve_default=False,
        ),
    ]
