# Generated by Django 4.1.7 on 2023-04-24 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0012_remove_savedjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 23, 16, 21, 505953, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
