# Generated by Django 4.1.7 on 2023-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0014_archivedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='industry',
            field=models.TextField(choices=[('Accountancy, banking and finance', 'Abf'), ('Business, consulting and management', 'Bcm'), ('Charity and voluntary work', 'Cvw'), ('Consumer goods and retail', 'Cgr'), ('Engineering and Construction', 'Ec'), ('Entertainment', 'Entertainment'), ('Environment and Agriculture', 'Ea'), ('Energy and Utilities', 'Eu')], default='Old'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='professional_summary',
            field=models.TextField(default='Old', max_length=200),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='role_type',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Old'),
        ),
    ]
