# Generated by Django 4.1.7 on 2023-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0016_alter_jobapplication_status_alter_jobseeker_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantcredential',
            name='credential',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicantcredential',
            name='credential_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='subject_of_study',
            field=models.TextField(blank=True, choices=[('Mass Communication', 'Mass Communication'), ('Accounting', 'Accounting'), ('Cosmetology', 'Cosmetology'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Economics', 'Economics'), ('Architecture', 'Architecture'), ('History', 'History'), ('Civil Engineering', 'Civil Engineering'), ('Biochemistry', 'Biochemistry'), ('Humanities', 'Humanities'), ('Microbiology', 'Microbiology'), ('Electrical Engineering', 'Electrical Engineering'), ('Veterinary Medicine', 'Veterinary Medicine'), ('Anatomy', 'Anatomy'), ('Business Administration', 'Business Administration'), ('Computer Science', 'Computer Science'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Pharmacy', 'Pharmacy'), ('Law', 'Law')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='year_of_graduation',
            field=models.CharField(blank=True, choices=[('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=200, null=True),
        ),
    ]
