# Generated by Django 4.1.7 on 2023-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekers', '0017_alter_applicantcredential_credential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
